# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 266)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 31, 34);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 24, 26);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(56, 58, 64);\n"
"    border: 2px solid rgb(56, 58, 64);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(76, 78, 84);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(66, 68, 74);\n"
"    color: rgb(30, 31, 34);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(-1, 7, -1, 7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(30, 31, 34);\n"
"    width: 7px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(43, 45, 49);\n"
"    min-height: 2px;\n"
"    border-radius: 2px;\n"
"    margin-right: 1px;\n"
"    margin-left: 1px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(63, 65, 69);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(53, 55, 59);\n"
"}\n"
"\n"
"/* horizontal SCROLLBAR */\n"
" QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(30, 31, 34);\n"
"    height: 10px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(43, 45, 49);\n"
"    min-width: 7px;\n"
"    border-radius: 2px;\n"
"    margin-top: 1px;\n"
"    margin-bottom: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(63, 65, 69);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(53, 55, 59);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 24, 26);\n"
"    border-radius: 5px;\n"
"}")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(30, 31, 34);\n"
"    width: 7px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(43, 45, 49);\n"
"    min-height: 2px;\n"
"    border-radius: 2px;\n"
"    margin-right: 1px;\n"
"    margin-left: 1px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(63, 65, 69);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(53, 55, 59);\n"
"}\n"
"\n"
"/* horizontal SCROLLBAR */\n"
" QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(30, 31, 34);\n"
"    height: 10px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(43, 45, 49);\n"
"    min-width: 7px;\n"
"    border-radius: 2px;\n"
"    margin-top: 1px;\n"
"    margin-bottom: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(63, 65, 69);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(53, 55, 59);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}\n"
"\n"
"QListWidget {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 24, 26);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_3.addWidget(self.listWidget_2, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "  №0  "))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Form", "  ->  \n"
"  ->  \n"
"  ->  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
