# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1_p.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 626)
        MainWindow.setStyleSheet("background-color: rgb(11, 18, 11);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 0, 6, 6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(23, 25))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem = QtWidgets.QSpacerItem(20, 537, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(686, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem1, 1, 2, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_12, icon, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.84, x1:0, y2:1, stop:0 rgba(21, 28, 21, 255), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setContentsMargins(0, 3, 0, 4)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_4.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_3, icon1, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_6.setContentsMargins(0, 5, 0, 10)
        self.gridLayout_6.setHorizontalSpacing(9)
        self.gridLayout_6.setVerticalSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listWidget = QtWidgets.QListWidget(self.tab_7)
        self.listWidget.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_7)
        self.textBrowser.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 0, 2, 3, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_11.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/SHARE.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_7.setContentsMargins(0, 5, 0, 10)
        self.gridLayout_7.setHorizontalSpacing(9)
        self.gridLayout_7.setVerticalSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_8)
        self.listWidget_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_7.addWidget(self.listWidget_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(31, 48, 31);\n"
"border-radius: 0.1px;\n"
"color: rgb(174, 180, 128);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_8)
        self.textBrowser_3.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_7.addWidget(self.textBrowser_3, 0, 1, 3, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_8)
        self.progressBar_2.setMaximumSize(QtCore.QSize(16777215, 3))
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setFormat("")
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_7.addWidget(self.progressBar_2, 1, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.gridLayout_5.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/url.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_6, icon5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setContentsMargins(0, 3, 0, 4)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setToolTipDuration(0)
        self.textBrowser_4.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_4.setLineWidth(0)
        self.textBrowser_4.setAcceptRichText(True)
        self.textBrowser_4.setCursorWidth(1)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_8.addWidget(self.textBrowser_4, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_4, icon6, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 2, 0, 1, 3)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_4.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_14.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.progressBar = QtWidgets.QProgressBar(self.tab_9)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_14.addWidget(self.progressBar, 2, 0, 1, 2)
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_5.setMaximumSize(QtCore.QSize(43, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2.5px solid rgba(42, 69, 38);\n"
"border-radius: 6px;")
        self.spinBox_5.setFrame(False)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(9999)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_14.addWidget(self.spinBox_5, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem3, 1, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(681, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_9)
        self.frame.setStyleSheet("background-color: rgb(17, 24, 16);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(True)
        self.pushButton.setStyleSheet("background-color: rgb(17, 24, 16);\n"
"border-radius: 10px;")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Android/res/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 3, 0, 1, 2)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_10)
        self.progressBar_3.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setFormat("")
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout_16.addWidget(self.progressBar_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_10)
        self.frame_2.setStyleSheet("background-color: rgb(17, 24, 16);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setEnabled(True)
        self.pushButton_14.setStyleSheet("background-color: rgb(17, 24, 16);\n"
"border-radius: 10px;")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_15.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_15.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_2, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem5, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.checkBox = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border-radius: 6px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked {\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_18.addWidget(self.checkBox, 3, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setStyleSheet("border-radius: 10px;")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon7)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_18.addWidget(self.pushButton_15, 3, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(60, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem6, 3, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(41, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem7, 3, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem8, 4, 1, 1, 6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_18.addWidget(self.lineEdit_6, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem9, 3, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem10, 0, 0, 1, 7)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem11, 2, 0, 1, 7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_11)
        self.spinBox_4.setMaximumSize(QtCore.QSize(43, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2.5px solid rgba(42, 69, 38);\n"
"border-radius: 6px;")
        self.spinBox_4.setFrame(False)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(9999)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.label = QtWidgets.QLabel(self.tab_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setIndent(8)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout_18.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.gridLayout_2.addWidget(self.tabWidget_4, 5, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem12, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(21, 24, 21);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 14px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 59, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(60, 70, 60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(69, 79, 69);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"QWidget {\n"
"    color: rgb(116, 138, 122);\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 756, 698))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setContentsMargins(8, 7, 8, 9)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem13 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem13, 6, 0, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 28, 0, 1, 4)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: rgb(217, 224, 215);\n"
"    background-color: rgb(42, 69, 38);\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(217, 224, 215);\n"
"    background-color: rgba(42, 69, 38, 150);\n"
"    border-radius: 1px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_9.addWidget(self.pushButton_3, 42, 0, 1, 4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setStyleSheet("color: rgb(217, 224, 215);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_9.addWidget(self.lineEdit_2, 7, 0, 1, 4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setStyleSheet("color: rgb(217, 224, 215);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_9.addWidget(self.lineEdit_4, 3, 0, 1, 4)
        self.radioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border-radius: 6px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_9.addWidget(self.radioButton, 32, 0, 1, 4)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setStyleSheet("background-color: rgb(42, 69, 38);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_9.addWidget(self.line_4, 29, 0, 1, 4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_2.setStyleSheet("QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border-radius: 6px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: qradialgradient(spread:pad, cx:0.50, cy:0.50, radius:0.50, fx:0.500, fy:0.500, stop:0.6 rgba(21, 37, 21, 255), stop:0.501 rgba(51, 74, 51, 255));\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_9.addWidget(self.radioButton_2, 35, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 39, 0, 1, 4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 14, 1, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(24, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 36, 1, 2, 3)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setMaximumSize(QtCore.QSize(55, 16777215))
        self.pushButton_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_10.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_10.setIcon(icon8)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_9.addWidget(self.pushButton_10, 34, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setMaximumSize(QtCore.QSize(55, 16777215))
        self.pushButton_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_8.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon9)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_9.addWidget(self.pushButton_8, 31, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(0, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem16, 33, 0, 1, 4)
        spacerItem17 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem17, 4, 0, 1, 4)
        spacerItem18 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem18, 30, 0, 1, 4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_2.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setFrame(False)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setReadOnly(True)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMaximum(20)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_9.addWidget(self.spinBox_2, 16, 3, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setFrame(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setReadOnly(True)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_9.addWidget(self.spinBox, 18, 3, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_3.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setFrame(False)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setReadOnly(True)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(5)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_9.addWidget(self.spinBox_3, 26, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setStyleSheet("background-color: rgb(42, 69, 38);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_9.addWidget(self.line_6, 40, 0, 1, 4)
        spacerItem19 = QtWidgets.QSpacerItem(0, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem19, 41, 0, 1, 4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setStyleSheet("color: rgb(217, 224, 215);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_9.addWidget(self.lineEdit_3, 5, 0, 1, 4)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setStyleSheet("background-color: rgb(42, 69, 38);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_9.addWidget(self.line_7, 1, 0, 1, 4)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem20, 9, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 10, 0, 1, 4)
        spacerItem21 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem21, 13, 0, 1, 4)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setStyleSheet("background-color: rgb(42, 69, 38);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 12, 0, 1, 4)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem22, 38, 0, 1, 4)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem23, 27, 0, 1, 4)
        spacerItem24 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem24, 2, 0, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon10)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_9.addWidget(self.pushButton_4, 14, 0, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_3.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalSlider_3.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: rgb(170, 85, 0);\n"
"    margin: 0px 6;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background: green;\n"
"    margin: -7px -6px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"    background-color: rgb(17, 24, 16);\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"    background: rgb(112, 187, 100);\n"
"}")
        self.horizontalSlider_3.setMaximum(5)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_9.addWidget(self.horizontalSlider_3, 18, 0, 1, 3)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: rgb(170, 85, 0);\n"
"    margin: 0px 6;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background: green;\n"
"    margin: -7px -6px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"    background-color: rgb(17, 24, 16);\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"    background: rgb(112, 187, 100);\n"
"}")
        self.horizontalSlider_2.setMaximum(20)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_9.addWidget(self.horizontalSlider_2, 16, 0, 1, 3)
        self.horizontalSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: rgb(170, 85, 0);\n"
"    margin: 0px 6;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background: green;\n"
"    margin: -7px -6px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"    background-color: rgb(17, 24, 16);\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"    background: rgb(112, 187, 100);\n"
"}")
        self.horizontalSlider.setMaximum(5)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_9.addWidget(self.horizontalSlider, 26, 0, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_9.addWidget(self.pushButton_5, 17, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("res/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon12)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_9.addWidget(self.pushButton_6, 25, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setContentsMargins(0, 3, 0, 5)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toolBox = QtWidgets.QToolBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    background-color: rgb(11, 18, 11); \n"
"}\n"
"QToolBox::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.79, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 788, 514))
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_3 = QtWidgets.QListWidget(self.page)
        self.listWidget_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_12.addWidget(self.listWidget_3, 0, 0, 5, 1)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_6.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayout_12.addWidget(self.textBrowser_6, 0, 1, 5, 1)
        spacerItem25 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem25, 0, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.page)
        self.pushButton_13.setStyleSheet("border-radius: 1px;")
        self.pushButton_13.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("res/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_13.setIcon(icon13)
        self.pushButton_13.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_12.addWidget(self.pushButton_13, 1, 2, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(0, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem26, 2, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.page)
        self.pushButton_12.setStyleSheet("border-radius: 1px;")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon2)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_12.addWidget(self.pushButton_12, 3, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 362, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem27, 4, 2, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 117, 87))
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.listWidget_4 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_4.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_13.addWidget(self.listWidget_4, 0, 0, 1, 1)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_5.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.gridLayout_13.addWidget(self.textBrowser_5, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_11.addWidget(self.toolBox, 2, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.tab_5)
        self.line_8.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_11.addWidget(self.line_8, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(0, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem28, 1, 0, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("res/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_5, icon14, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Version: 0.1.1"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Відповіді"))
        self.pushButton_2.setText(_translate("MainWindow", "Отримати відповіді"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Можливі відповіді"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "Звичайний пошук"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "url:"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Пошук по url"))
        self.checkBox.setText(_translate("MainWindow", "Автоматичний режим"))
        self.label.setText(_translate("MainWindow", "Затримка в секундах"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Пошук через браузер"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Пошук теста"))
        self.label_8.setText(_translate("MainWindow", "Браузер"))
        self.pushButton_3.setText(_translate("MainWindow", "Зберегти налаштування"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "   💻 user name:"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "   📧 email:"))
        self.radioButton.setText(_translate("MainWindow", "Google Chrome"))
        self.radioButton_2.setText(_translate("MainWindow", "Mozilla Firefox"))
        self.label_9.setText(_translate("MainWindow", "Реєстрація"))
        self.label_10.setText(_translate("MainWindow", "V.0.1.7 - BETA"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "   🔑 password:"))
        self.label_7.setText(_translate("MainWindow", "Кількість сторінок, що скануються"))
        self.pushButton_4.setText(_translate("MainWindow", "     Naurok       "))
        self.pushButton_5.setText(_translate("MainWindow", "    Google      "))
        self.pushButton_6.setText(_translate("MainWindow", "      Bing          "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Налаштування"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Історія"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Перегляд історії"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
