# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Test-Finder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(11, 18, 11);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 0, 6, 6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(23, 25))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem = QtWidgets.QSpacerItem(20, 537, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 3, 0, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_17.addWidget(self.pushButton_8, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem1, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_17.addWidget(self.pushButton_9, 2, 3, 1, 1)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_12)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(444, 444))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(444, 444))
        self.textBrowser_5.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    border-image: url(\"res/icon.png\");\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.gridLayout_17.addWidget(self.textBrowser_5, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(686, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 3, 2, 1, 3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_12, icon2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.84, x1:0, y2:1, stop:0 rgba(21, 28, 21, 255), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setContentsMargins(0, 3, 0, 4)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_4.addWidget(self.textEdit_2, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_3, icon3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_7.setContentsMargins(0, 5, 0, 10)
        self.gridLayout_7.setHorizontalSpacing(9)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/SHARE.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout_7.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 3, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_8)
        self.listWidget_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 0.1px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(11, 18, 11);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 0.1px;\n"
"}")
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_7.addWidget(self.listWidget_2, 0, 1, 4, 1)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_6.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.84, x1:0, y2:1, stop:0 rgba(21, 28, 21, 255), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_6.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_6.setIconSize(QtCore.QSize(17, 17))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.tab_13)
        self.frame_3.setStyleSheet("background-color: rgb(14, 22, 14);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_9.setContentsMargins(9, 2, 3, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/url2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_9.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_9.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_3, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_13)
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_18.addWidget(self.line_3, 1, 0, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.tab_13)
        self.progressBar_4.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar_4.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    background: rgb(14, 22, 14)\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setFormat("")
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout_18.addWidget(self.progressBar_4, 2, 0, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_3.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_18.addWidget(self.textEdit_3, 3, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/url3.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_6.addTab(self.tab_13, icon7, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setHorizontalSpacing(4)
        self.gridLayout_19.setVerticalSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_11 = QtWidgets.QLabel(self.tab_14)
        self.label_11.setStyleSheet("background-color: rgb(134, 32, 24);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_19.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_14)
        self.label_8.setObjectName("label_8")
        self.gridLayout_19.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_14)
        self.label_7.setObjectName("label_7")
        self.gridLayout_19.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_14)
        self.label_9.setStyleSheet("background-color: rgb(34, 92, 44);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_19.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_14)
        self.label_10.setStyleSheet("background-color: rgb(44, 62, 44);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_19.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_14)
        self.label_6.setObjectName("label_6")
        self.gridLayout_19.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_14)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_14)
        self.label_13.setStyleSheet("background-color: rgb(24, 32, 24);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 2, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem7, 2, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_14)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_21.setHorizontalSpacing(6)
        self.gridLayout_21.setVerticalSpacing(12)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_3.setStyleSheet("QRadioButton::indicator {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border: 2px solid rgb(51, 67, 51);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(91, 127, 91);\n"
"}\n"
"QRadioButton {\n"
"    background-color: rgb(11, 18, 11);\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_6.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_5.setStyleSheet("QRadioButton::indicator {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border: 2px solid rgb(51, 67, 51);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(91, 127, 91);\n"
"}\n"
"QRadioButton {\n"
"    background-color: rgb(11, 18, 11);\n"
"}")
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_6.addWidget(self.radioButton_5, 1, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_6.setStyleSheet("QRadioButton::indicator {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border: 2px solid rgb(51, 67, 51);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(91, 127, 91);\n"
"}\n"
"QRadioButton {\n"
"    background-color: rgb(11, 18, 11);\n"
"}")
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_6.addWidget(self.radioButton_6, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.frame_4, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_21.addWidget(self.label_14, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem8, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton::indicator {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border: 2px solid rgb(51, 67, 51);\n"
"    border-radius: 6px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(91, 127, 91);\n"
"}\n"
"QRadioButton {\n"
"    background-color: rgb(11, 18, 11);\n"
"}")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_15.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("QRadioButton::indicator {\n"
"    background-color: rgb(21, 37, 21);\n"
"    border: 2px solid rgb(51, 67, 51);\n"
"    border-radius: 6px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(91, 127, 91);\n"
"}\n"
"QRadioButton {\n"
"    background-color: rgb(11, 18, 11);\n"
"}")
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_15.addWidget(self.radioButton_4, 0, 1, 1, 1)
        self.gridLayout_21.addWidget(self.frame_2, 4, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_5, 1, 0, 1, 3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_6.addTab(self.tab_14, icon8, "")
        self.gridLayout_7.addWidget(self.tabWidget_6, 0, 2, 5, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.gridLayout_5.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/url.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_6, icon9, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setContentsMargins(0, 3, 0, 4)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setToolTipDuration(0)
        self.textEdit_4.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textEdit_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_4.setLineWidth(0)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_8.addWidget(self.textEdit_4, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_4, icon10, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 2, 0, 1, 3)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_4.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setStyleSheet("QWidget {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgba(255, 255, 255, 160);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: rgb(11, 18, 11);\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.86, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_14.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.progressBar = QtWidgets.QProgressBar(self.tab_9)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_14.addWidget(self.progressBar, 2, 0, 1, 2)
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_5.setMaximumSize(QtCore.QSize(43, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2.5px solid rgba(42, 69, 38);\n"
"border-radius: 6px;")
        self.spinBox_5.setFrame(False)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(9999)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_14.addWidget(self.spinBox_5, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem9, 1, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(681, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem10, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_9)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame.setStyleSheet("background-color: rgb(17, 24, 16);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet("background-color: rgb(17, 24, 16);\n"
"border-radius: 10px;")
        self.pushButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 3, 0, 1, 2)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_16.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_10)
        self.progressBar_3.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
"    color: rgb(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(112, 187, 100);\n"
"    width: 5px;\n"
"}")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setFormat("")
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout_16.addWidget(self.progressBar_3, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_10)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_6.setStyleSheet("background-color: rgb(17, 24, 16);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 24, 16);")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setMinimumSize(QtCore.QSize(22, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_10.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setMinimumSize(QtCore.QSize(22, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_10.addWidget(self.pushButton_10, 0, 4, 1, 1)
        self.gridLayout_16.addWidget(self.frame_6, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem12, 1, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_10, "")
        self.gridLayout_2.addWidget(self.tabWidget_4, 5, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setContentsMargins(0, 3, 0, 5)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toolBox = QtWidgets.QToolBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    background-color: rgb(11, 18, 11); \n"
"}\n"
"QToolBox::tab {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(11, 18, 11);\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.79, x1:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.495 rgba(0, 0, 0, 0), stop:0.505 rgba(66, 108, 62, 220), stop:1 rgba(66, 108, 62, 220));\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 914, 495))
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_3 = QtWidgets.QListWidget(self.page)
        self.listWidget_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    height: 13px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(14, 22, 14);\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    color: rgb(204, 236, 168);\n"
"    outline: none;\n"
"    border-radius: 0.1px;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(204, 236, 168);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 0.1px;\n"
"}")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_12.addWidget(self.listWidget_3, 0, 0, 7, 1)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_6.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(19, 24, 19);\n"
"    width: 13px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(44, 49, 45);\n"
"    min-height: 18px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: rgb(204, 236, 168);\n"
"    background-color: rgb(14, 22, 14);\n"
"}")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayout_12.addWidget(self.textBrowser_6, 0, 1, 7, 1)
        spacerItem14 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem14, 0, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.page)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_13.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("res/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_12.addWidget(self.pushButton_13, 1, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 362, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem15, 2, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.page)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    border-radius: 0.1px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2.5px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(31, 48, 31, 90);\n"
"    border: 2.5px solid rgba(31, 48, 31, 90);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_12.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.gridLayout_11.addWidget(self.toolBox, 2, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.tab_5)
        self.line_8.setStyleSheet("background-color: rgb(19, 24, 19);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_11.addWidget(self.line_8, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(0, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem16, 1, 0, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("res/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_5, icon13, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test-Finder"))
        self.label_2.setText(_translate("MainWindow", "Version: 0.1.4"))
        self.pushButton_9.setText(_translate("MainWindow", "Update"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Помилка"))
        self.label_7.setText(_translate("MainWindow", "Є невеликі збіги"))
        self.label_6.setText(_translate("MainWindow", "Майже 100% збіг"))
        self.label_12.setText(_translate("MainWindow", "Немає збігів"))
        self.radioButton_3.setText(_translate("MainWindow", "Кількістю збігів"))
        self.radioButton_5.setText(_translate("MainWindow", "Кількістю запитань"))
        self.radioButton_6.setText(_translate("MainWindow", "Не сортувати"))
        self.label_14.setText(_translate("MainWindow", "Сортування тестів за:"))
        self.radioButton_2.setText(_translate("MainWindow", "За зростанням"))
        self.radioButton_4.setText(_translate("MainWindow", "За зменшенням"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Можливі відповіді"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "Звичайний пошук"))
        self.label_16.setText(_translate("MainWindow", "0/0"))
        self.pushButton_7.setText(_translate("MainWindow", "<"))
        self.pushButton_10.setText(_translate("MainWindow", ">"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Пошук за текстом"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Пошук теста"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Історія"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
